"""
Global Configuration for StadiumOS
"""

# AI Settings
AI_CRITICAL_EVENT_LIMIT = 10
AI_WARNING_EVENT_LIMIT = 15
DEFAULT_CONFIDENCE_THRESHOLD = 0.85

# System Settings
ENABLE_AUTO_REFRESH = True
REFRESH_INTERVAL_SECONDS = 2
