import uuid
from typing import List, Optional, Tuple

from backend.threat_engine.models import OperationalThreat, RecommendedAction, ThreatExplanationResponse
from backend.threat_engine.interfaces import IActionRecommender
from backend.threat_engine.threat_explainer import AIThreatExplainer

class ActionRecommender(IActionRecommender):
    """
    Engine that generates ranked operational action lists.
    It combines the strict, deterministic playbook actions embedded in a Threat
    with the rich, dynamic situational actions generated by the AI Brain.
    """
    def __init__(self, explainer: Optional[AIThreatExplainer] = None):
        self.explainer = explainer or AIThreatExplainer()

    def _create_deterministic_action(self, threat: OperationalThreat) -> RecommendedAction:
        """Converts the hardcoded rule payload into a rich Action format."""
        return RecommendedAction(
            action_id=f"ACT-DET-{str(uuid.uuid4())[:6].upper()}",
            rank=1,  # Playbook actions are always rank 1 (highest priority)
            title=f"Execute Playbook: {threat.category} Protocol",
            description=threat.recommended_action,
            priority="CRITICAL",
            estimated_impact="Immediate rule-based mitigation.",
            estimated_resolution_time_mins=5,
            required_resources=["Command Center"],
            dependency=None,
            risk_reduction_score=50.0,
            is_ai_generated=False
        )

    def generate_recommendations(self, threat: OperationalThreat, risk_score: float) -> Tuple[List[RecommendedAction], Optional[ThreatExplanationResponse]]:
        """
        Orchestrates the combination of deterministic rules and AI explanations.
        """
        final_actions: List[RecommendedAction] = []
        explanation_response = None
        
        # 1. Always inject the deterministic playbook action first
        det_action = self._create_deterministic_action(threat)
        final_actions.append(det_action)
        
        # 2. Query the AI Explainer for dynamic situational actions
        try:
            explanation_response = self.explainer.explain_threat(threat, risk_score)
            
            ai_actions = explanation_response.recommended_actions
            ai_actions.sort(key=lambda x: x.rank)
            
            for index, action in enumerate(ai_actions):
                action.rank = index + 2 
                action.is_ai_generated = True
                
                if not action.action_id.startswith("ACT-"):
                    action.action_id = f"ACT-AI-{str(uuid.uuid4())[:6].upper()}"
                    
                final_actions.append(action)
                
        except Exception as e:
            pass
            
        final_actions.sort(key=lambda x: x.rank)
        
        return final_actions, explanation_response
