from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional
from enum import Enum

class ThreatSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class RuleCondition(BaseModel):
    """A deterministic evaluation condition."""
    field: str = Field(description="The event property to check (e.g. 'category.value')")
    operator: str = Field(description="Logic operator: '==', '>', '<', 'contains', 'in'")
    value: Any = Field(description="The value to compare against")

class SecurityRule(BaseModel):
    """Configuration for deterministic threat detection."""
    rule_id: str
    name: str
    enabled: bool = True
    category: str
    conditions: List[RuleCondition]
    threshold_count: int = Field(default=1, description="Number of matches required")
    threshold_window_sec: int = Field(default=0, description="Time window in seconds (0 = immediate)")
    severity: ThreatSeverity
    priority: int
    generated_threat_name: str
    recommended_action: str

class OperationalThreat(BaseModel):
    """A detected and verified security or operational threat."""
    threat_id: str
    rule_id: str
    name: str
    category: str
    severity: ThreatSeverity
    priority: int
    location: str
    timestamp: str
    description: str
    recommended_action: str
    status: str = "DETECTED"
    triggering_events: List[str] = Field(description="List of Event IDs that triggered this threat")

class SubsystemRisk(BaseModel):
    """Deterministic risk evaluation for a specific stadium subsystem."""
    category: str = Field(description="e.g. CROWD, GATE, SECURITY")
    score: float = Field(description="Risk score from 0.0 to 100.0")
    factors: List[str] = Field(description="Explainable list of factors contributing to this score")

class RiskCalculationResult(BaseModel):
    """The final deterministic evaluation of the stadium's operational risk."""
    overall_score: float = Field(description="Global risk score from 0.0 to 100.0")
    risk_category: str = Field(description="NOMINAL, ELEVATED, HIGH, or CRITICAL")
    trend: str = Field(description="STABLE, RISING, or FALLING")
    confidence_score: float = Field(description="Data completeness confidence 0.0 to 1.0")
    subsystem_risks: List[SubsystemRisk]
    explainability_log: List[str] = Field(description="Transparent log of how the overall score was mathematically computed")

class IncidentStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"

class IncidentTimelineEvent(BaseModel):
    timestamp: str
    action: str
    actor: str
    notes: Optional[str] = None

class SecurityIncident(BaseModel):
    incident_id: str
    threat_id: str
    title: str
    status: IncidentStatus
    severity: ThreatSeverity
    priority: int
    created_at: str
    updated_at: str
    owner: Optional[str] = None
    timeline: List[IncidentTimelineEvent]

class RecommendedAction(BaseModel):
    """A rich, rankable operational action with dependencies and resource requirements."""
    action_id: str
    rank: int = Field(description="1 is highest priority")
    title: str = Field(description="Short, imperative title (e.g., 'Open Gate C')")
    description: str = Field(description="Detailed execution instructions")
    priority: str = Field(description="HIGH, MEDIUM, LOW")
    estimated_impact: str = Field(description="What happens if executed")
    estimated_resolution_time_mins: int = Field(description="Time to complete in minutes")
    required_resources: List[str] = Field(description="e.g. 'Security Team Alpha', 'Medical Staff'")
    dependency: Optional[str] = Field(default=None, description="Action ID of prerequisite action")
    risk_reduction_score: float = Field(description="Estimated risk points reduced if executed")
    is_ai_generated: bool = Field(default=True, description="False if from deterministic rule, True if from AI")

class ThreatExplanationResponse(BaseModel):
    """Structured AI output for explaining a verified threat."""
    summary: str = Field(description="Executive summary of the threat")
    reasoning: str = Field(description="Detailed reasoning based strictly on the provided context")
    recommended_actions: List[RecommendedAction] = Field(description="Ranked list of rich operational actions")
    mitigation_steps: List[str] = Field(description="Long-term mitigation steps")
    operational_impact: str = Field(description="Estimated impact on stadium operations")
    estimated_resolution: str = Field(description="Estimated time or condition for resolution")
    confidence: float = Field(description="Confidence score from 0.0 to 1.0")

class EnrichedOperationalThreat(BaseModel):
    """
    The master unified payload generated by the Threat Engine Orchestrator.
    Combines deterministic detection, mathematical risk, lifecycle status, 
    and AI generative intelligence into a single machine-readable object.
    """
    threat_id: str
    incident_id: str
    rule_name: str
    risk_score: float
    severity: ThreatSeverity
    priority: int
    confidence: float
    recommended_actions: List[RecommendedAction]
    current_status: IncidentStatus
    reasoning: str
    mitigation_plan: List[str]
    timeline: List[IncidentTimelineEvent]
